// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// objective
double objective(const arma::mat& X, const Rcpp::List& mu, const Rcpp::List& Sigma, const arma::mat& pi_groups, const arma::mat& W, const arma::uvec& groups, const arma::mat& Q);
RcppExport SEXP _ssMRCD_objective(SEXP XSEXP, SEXP muSEXP, SEXP SigmaSEXP, SEXP pi_groupsSEXP, SEXP WSEXP, SEXP groupsSEXP, SEXP QSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type pi_groups(pi_groupsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Q(QSEXP);
    rcpp_result_gen = Rcpp::wrap(objective(X, mu, Sigma, pi_groups, W, groups, Q));
    return rcpp_result_gen;
END_RCPP
}
// w_step
arma::mat w_step(arma::mat& X, Rcpp::List& mu, Rcpp::List& Sigma, arma::mat& pi_groups, arma::mat& W, arma::uvec& groups, arma::mat& Q, arma::vec& h);
RcppExport SEXP _ssMRCD_w_step(SEXP XSEXP, SEXP muSEXP, SEXP SigmaSEXP, SEXP pi_groupsSEXP, SEXP WSEXP, SEXP groupsSEXP, SEXP QSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< Rcpp::List& >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type pi_groups(pi_groupsSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Q(QSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(w_step(X, mu, Sigma, pi_groups, W, groups, Q, h));
    return rcpp_result_gen;
END_RCPP
}
// probabs
arma::mat probabs(const arma::mat& X, const Rcpp::List& mu, const Rcpp::List& Sigma, const arma::mat& pi_groups, const arma::mat& W, const arma::uvec& groups);
RcppExport SEXP _ssMRCD_probabs(SEXP XSEXP, SEXP muSEXP, SEXP SigmaSEXP, SEXP pi_groupsSEXP, SEXP WSEXP, SEXP groupsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type pi_groups(pi_groupsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type groups(groupsSEXP);
    rcpp_result_gen = Rcpp::wrap(probabs(X, mu, Sigma, pi_groups, W, groups));
    return rcpp_result_gen;
END_RCPP
}
// pis
arma::mat pis(const arma::mat& probs, const arma::uvec& groups, double alpha);
RcppExport SEXP _ssMRCD_pis(SEXP probsSEXP, SEXP groupsSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type probs(probsSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type groups(groupsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(pis(probs, groups, alpha));
    return rcpp_result_gen;
END_RCPP
}
// RCOV
Rcpp::List RCOV(const arma::mat& XX, const arma::vec& vMu, double rho, const arma::mat& mT, double scfac);
RcppExport SEXP _ssMRCD_RCOV(SEXP XXSEXP, SEXP vMuSEXP, SEXP rhoSEXP, SEXP mTSEXP, SEXP scfacSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type XX(XXSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type vMu(vMuSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mT(mTSEXP);
    Rcpp::traits::input_parameter< double >::type scfac(scfacSEXP);
    rcpp_result_gen = Rcpp::wrap(RCOV(XX, vMu, rho, mT, scfac));
    return rcpp_result_gen;
END_RCPP
}
// objective_matrix
double objective_matrix(const List& matrix_list, double lambda, const arma::mat& weights);
RcppExport SEXP _ssMRCD_objective_matrix(SEXP matrix_listSEXP, SEXP lambdaSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type matrix_list(matrix_listSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(objective_matrix(matrix_list, lambda, weights));
    return rcpp_result_gen;
END_RCPP
}
// objective_init
double objective_init(const List& init_object, double lambda, const arma::mat& weights);
RcppExport SEXP _ssMRCD_objective_init(SEXP init_objectSEXP, SEXP lambdaSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type init_object(init_objectSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(objective_init(init_object, lambda, weights));
    return rcpp_result_gen;
END_RCPP
}
// dist_cstep
arma::vec dist_cstep(const List& init, int i, double lambda, const arma::mat& weights);
RcppExport SEXP _ssMRCD_dist_cstep(SEXP initSEXP, SEXP iSEXP, SEXP lambdaSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type init(initSEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(dist_cstep(init, i, lambda, weights));
    return rcpp_result_gen;
END_RCPP
}
// cstep
List cstep(const List& init, int maxcsteps, const arma::uvec& which_indices, double lambda, const arma::mat& weights, const arma::mat& mT);
RcppExport SEXP _ssMRCD_cstep(SEXP initSEXP, SEXP maxcstepsSEXP, SEXP which_indicesSEXP, SEXP lambdaSEXP, SEXP weightsSEXP, SEXP mTSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type init(initSEXP);
    Rcpp::traits::input_parameter< int >::type maxcsteps(maxcstepsSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type which_indices(which_indicesSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mT(mTSEXP);
    rcpp_result_gen = Rcpp::wrap(cstep(init, maxcsteps, which_indices, lambda, weights, mT));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ssMRCD_objective", (DL_FUNC) &_ssMRCD_objective, 7},
    {"_ssMRCD_w_step", (DL_FUNC) &_ssMRCD_w_step, 8},
    {"_ssMRCD_probabs", (DL_FUNC) &_ssMRCD_probabs, 6},
    {"_ssMRCD_pis", (DL_FUNC) &_ssMRCD_pis, 3},
    {"_ssMRCD_RCOV", (DL_FUNC) &_ssMRCD_RCOV, 5},
    {"_ssMRCD_objective_matrix", (DL_FUNC) &_ssMRCD_objective_matrix, 3},
    {"_ssMRCD_objective_init", (DL_FUNC) &_ssMRCD_objective_init, 3},
    {"_ssMRCD_dist_cstep", (DL_FUNC) &_ssMRCD_dist_cstep, 4},
    {"_ssMRCD_cstep", (DL_FUNC) &_ssMRCD_cstep, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_ssMRCD(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
